app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('authors/', include('authors.urls')),
    path('admin/', admin.site.urls),
]

# add media folder to url patterns to access media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#add statis files to url patterns to access static files (for production)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import handler400, handler403, handler404, handler500
from django.urls import path

from . import views

# urls.py do projeto
handler404 = views.error_404_view
handler500 = views.error_500_view
handler403 = views.error_403_view
handler400 = views.error_400_view

app_name = 'main'

urlpatterns = [
    path('', views.main_view, name='home'),
    path('search/', views.search, name='search'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
    path('category/<int:id>/', views.category, name='category'),


    # fixas
    path('sobre/', views.sobre_view, name='sobre'),
    path('contato/', views.contato_view, name='contato'),
]

app/templates/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://github.com/saulorj/" target="_blank" rel="noreferrer noopener">By Saulo Oliveira</a>
  </div>

  <div class="powered">
    <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
  </div>
</footer>

app/templates/partials/form.html
<div class="main-containt container">
    <form action="{{form_action}}" method="POST">
        {% csrf_token %}
        <div class="form-content form-grid">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{field}}
                    {% if field.help_text %}
                        <p class="help-text">{{ field.help_text }}</p>
                    {% endif %}
                    {{ field.errors }}
                </div>
            {% endfor %}
        </div>
        {% if form.errors %}
            <div class="form-content form-content-grid">
                <div class="form-group">
                    <div class="message message-error">
                        Por favor corrija os erros no formulário.
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="form-content form-content-grid">
            <div class="form-group">
                <button type="submit">Send</button>
            </div>
        </div>
    </form>
</div>

app/templates/partials/head.html
 {% load static %}

    <meta charset="utf-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/fontawesome.min.css" integrity="sha512-M5Kq4YVQrjg5c2wsZSn27Dkfm/2ALfxmun0vUE3mPiJyK53hQBHYCVAtvMYEC7ZXmYLg8DVG4tF8gD27WmDbsg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/brands.min.css" integrity="sha512-WxpJXPm/Is1a/dzEdhdaoajpgizHQimaLGL/QqUIAjIihlQqlPQb1V9vkGs9+VzXD7rgI6O+UsSKl4u5K36Ydw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/solid.min.css" integrity="sha512-EHa6vH03/Ty92WahM0/tet1Qicl76zihDCkBnFhN3kFGQkC+mc86d7V+6y2ypiLbk3h0beZAGdUpzfMcb06cMg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="{% static 'app/css/styles.css' %}">

app/templates/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
    <h1>
        <a href="{% url 'main:home' %}" class="main-logo">
        <i class="fa-solid fa-burger main-logo-icon"></i>
        <span class="main-logo-text">Melhores Receitas</span>
        </a>
    </h1>
    </div>
</header>

app/templates/partials/messages.html
    {% if messages %}
        <div class="main-content center container messages-container">
            {% for message in messages %}
                <div class="messages {{message.tags}}">
                    {{message}}
                </div>
            {% endfor %}
        </div>
    {% endif %}

app/templates/partials/pagination.html
    {% if recipes.has_other_pages %}
        <div class="pagination-content">
            <div class="container pagination">
                {% if pages.first_page_out_of_range %}
                    <a href="?page=1{% if add_qry %}{{ add_qry }}{% endif %}" class="page-link page-item">1</a>
                    <span class="page-item">...</span>
                {% endif %}
                {% for page in pages.pagination %}
                    <a href="?page={{page}}{% if add_qry %}{{ add_qry }}{% endif %}" class="page-link page-item {% if pages.current_page == page %} page-current{% endif %}">{{page}}</a>
                {% endfor %}
                {% if pages.last_page_out_of_range %}
                    <span class="page-item">...</span>
                    <a href="?page={{pages.total_pages}}{% if add_qry %}{{ add_qry }}{% endif %}" class="page-link page-item">{{pages.total_pages}}</a>
                {% endif %}
            </div>
        </div>
    {% endif %}

app/templates/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'main:recipe' recipe.id %}">
            <img src="{{recipe.cover.url}}" alt="Temporário">
        </a>
    </div>
    <div class="recipe-title-container">
        <a href="{% url 'main:recipe' recipe.id %}">
            <h2 class="recipe-title">{{recipe.title}}</h2>
        </a>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fa-solid fa-user"></i>
            {{recipe.author.first_name}}
        </span>
        <span class="recipe-author-item">
            <i class="fa-solid fa-calendar-alt"></i>
            {{recipe.created_at | date:"d/m/Y" }} ás {{recipe.created_at | time:"H:i"}}
        </span>
        <span class="recipe-author-item">
            <a href="{% url 'main:category' recipe.category.id %}">
                <i class="fa-solid fa-layer-group"></i>
                <span>{{recipe.category.name}}</span>
            </a>
        </span>
    </div>

    <div class="recipe-content">
        <p>
            {{recipe.description}}
        </p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fa-solid fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">{{recipe.preparation_time}} {{recipe.preparation_time_unit}}</div>
        </div>

        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fa-solid fa-pizza-slice"></i> Porçoes</h3>
            <div class="recipe-meta-text">{{recipe.servings}} {{recipe.servings_unit}}</div>
        </div>
    </div>
    {%if not is_detail_page %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'main:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {%  else %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{recipe.preparation_steps | safe}}
            {% else %}
                {{recipe.preparation_steps | linebreaksbr}}
            {% endif %}
        </div>
    {% endif %}
</div>

app/templates/partials/search_container.html
    <div class="search-container">
        <div class="container">
            <form action="{% url 'main:search'%}" class="search-form">
                <input type="search" name="q" class="search-input" placeholder="Pesquisar receitas..." value="{% if search_term %}{{ search_term }}{% endif %}" required>
                <button type="submit" class="search-button">
                    <i class="fa-solid fa-search"></i>
                </button>
            </form>
        </div>
    </div>